### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by louhz** [IHe-KaiI/RNHA_Dataset#1]
So i test this dataset with ngp and other multi view algorithm.
But with out bounding box or near, far the algorithm cannot converge.

So does dataset has a near far or bounding box setting？

**Comment by Miaoing** [comment]
Dear louhz,

Thank you for raising this issue.

To run ngp, it is necessary to modify its code in order to support different camera intrinsic parameters for each image. In this regard, a file named 'nerf_loader.cu' has been uploaded to this repository. You can replace your 'instant-ngp/src/nerf_loader.cu' with this file and rebuild ngp.

Considering the long capture period, it is understandable that different data may possess varying camera parameters, which makes it impossible to have a fixed bounding box. Nevertheless, we have an example bounding box calculated by ngp that might be helpful:

For the data xj0201e4gxgwr5nl.zip, the modified ngp algorithm resulted in the following bounding box:
cam_aabb=[min=[-1.98689,-1.66194,-0.0187217], max=[2.60669,2.71825,1.47449]]

Thank you for bringing this issue to our attention. We assure you that we will make every effort to promptly address it.

Best regards.
